output_dir: ./models/rugpt3small_full_toxicator
train_path: ./train.rugpt3small_toxicator.jsonl
val_path: ./val.rugpt3small_toxicator.jsonl

datasets:
  - name: evilfreelancer/toxicator-ru
    converter: impruver.instruction_to_messages

model:
  class: transformers.AutoModelForCausalLM
  name: ai-forever/rugpt3small_based_on_gpt2
  dtype: bf16

tokenizer:
  class: transformers.AutoTokenizer
  name: ai-forever/rugpt3small_based_on_gpt2

trainer:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 100
  save_steps: 100
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 5
  logging_steps: 1
  learning_rate: 0.0006
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 2000
  optim: paged_adamw_8bit
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.1

#ddp:
#  ddp_find_unused_parameters: false
