# Training time
# - 1x RTX 4090 ~ 21.9GiB

output_dir: ./models/ruGPT-3.5_13B_lora_fcot
train_path: ./train.ruGPT-3.5_13B_fcot.jsonl
val_path: ./val.ruGPT-3.5_13B_fcot.jsonl

datasets:
  - name: korotkov/glaive-function-calling-v2-ru-parsed
  - name: evilfreelancer/ru-chain-of-thought-sharegpt
    converter: impruver.conversations_to_messages
  - name: AiCloser/sharegpt_cot_dataset
    converter: impruver.conversations_to_messages
  - name: IlyaGusev/oasst2_ru_main_branch
    converter: impruver.dialog_to_messages
  - name: MexIvanov/Vezora-Tested-22k-Python-Alpaca-ru
    converter: impruver.instruction_to_messages

model:
  class: transformers.AutoModelForCausalLM
  name: ai-forever/ruGPT-3.5-13B
  load_in_4bit: true
  load_in_8bit: false
  dtype: bf16

lora:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.05
  bias: none
  target_modules: [ c_attn, c_fc, c_proj ]
  task_type: CAUSAL_LM

tokenizer:
  class: transformers.AutoTokenizer
  name: ai-forever/ruGPT-3.5-13B
  max_tokens_count: 1300

trainer:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 100
  save_steps: 100
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32
  logging_steps: 1
  learning_rate: 0.0002
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 16
  optim: adamw_8bit
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.08
  torch_compile: false

#ddp:
#  ddp_find_unused_parameters: false
