output_dir: ./models/rugpt3large_full
train_path: ./train.rugpt3large.jsonl
val_path: ./val.rugpt3large.jsonl

datasets:
  - name: IlyaGusev/ru_turbo_alpaca
    converter: impruver.instruction_to_messages
    only_target_loss: false

model:
  class: transformers.GPT2LMHeadModel
  dtype: bf16

tokenizer:
  class: transformers.GPT2LMHeadModel
  name: ai-forever/rugpt3large_based_on_gpt2

trainer:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 10
  save_steps: 10
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  logging_steps: 1
  learning_rate: 0.00005
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 16
  optim: paged_adamw_8bit
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.08

#ddp:
#  ddp_find_unused_parameters: false
