datasets:
  - class: transformers.AutoModelForCausalLM
    name: mahiatlinux/Reflection-Dataset-ShareGPT-v2
    # Name of split in dataset
    split: train # you may limit these split like train[:1000] - this mean get first 1000 elements from train split
    # Max tokens per single conversation (dataset level)
    max_tokens_count: 2048

model:
  class: transformers.AutoModelForCausalLM
  name: ai-forever/rugpt3small_based_on_gpt2
  load_in_4bit: false
  load_in_8bit: true
  dtype: fp16
  #attn_implementation: flash_attention_2

lora:
  r: 32
  lora_alpha: 16
  lora_dropout: 0.0
  bias: none
  target_modules: [ c_attn, c_proj, c_fc ]
  modules_to_save: [ lm_head ]

tokenizer:
  class: transformers.AutoTokenizer
  name: ai-forever/rugpt3small_based_on_gpt2
  # Max tokens per single conversation (tokenizer level)
  max_tokens_count: 2048

trainer:
  eval_strategy: steps
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 64
  eval_steps: 16
  save_steps: 16
  logging_steps: 1
  learning_rate: 0.00001
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 16
  optim: paged_adamw_8bit
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.08
