output_dir: ./models/rugpt3large_full
train_path: ./train.jsonl
val_path: ./val.jsonl

datasets:
  - name: IlyaGusev/ru_turbo_alpaca
    converter: impruver.data.instruction_to_messages
  - name: IlyaGusev/ru_turbo_alpaca_evol_instruct
    converter: impruver.data.instruction_to_messages
  - name: IlyaGusev/ru_turbo_saiga
    converter: impruver.data.dialog_to_messages
  - name: IlyaGusev/ru_sharegpt_cleaned
    converter: impruver.data.dialog_to_messages
  - name: IlyaGusev/oasst1_ru_main_branch
    converter: impruver.data.dialog_to_messages
  - name: lksy/ru_instruct_gpt4
    converter: impruver.data.instruction_to_messages
#  - name: IlyaGusev/gpt_roleplay_realm
#    converter: impruver.data.char_dialog_to_messages
#    split: ru

model:
  class: transformers.AutoModelForCausalLM
  name: ai-forever/rugpt3large_based_on_gpt2
  dtype: bf16

tokenizer:
  class: transformers.AutoTokenizer
  name: ai-forever/rugpt3large_based_on_gpt2
  # Max tokens per single conversation (tokenizer level)
  max_tokens_count: 2048

trainer:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 10
  save_steps: 10
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 128
  logging_steps: 1
  learning_rate: 0.00005
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 16
  optim: paged_adamw_8bit
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.08

#ddp:
#  ddp_find_unused_parameters: false
