# Training time
# - 1x RTX 3050 ~ 6.8GiB ~ 4h 9m (train_batch_size: 1)
# - 1x RTX 4090 ~ 20.5GiB ~ 37m

output_dir: ./models/rugpt3small_full_fc
train_path: ./train.rugpt3small_fc.jsonl
val_path: ./val.rugpt3small_fc.jsonl

datasets:
  - name: korotkov/glaive-function-calling-v2-ru-parsed
    split: train

model:
  class: transformers.AutoModelForCausalLM
  name: ai-forever/rugpt3small_based_on_gpt2
  dtype: bf16

tokenizer:
  class: transformers.AutoTokenizer
  name: ai-forever/rugpt3small_based_on_gpt2

trainer:
  eval_strategy: steps
  save_strategy: steps
  eval_steps: 100
  save_steps: 100
  per_device_train_batch_size: 7
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 5
  logging_steps: 1
  learning_rate: 0.0006
  num_train_epochs: 2
  lr_scheduler_type: cosine
  warmup_steps: 2000
  optim: paged_adamw_8bit
  metric_for_best_model: eval_loss
  load_best_model_at_end: true
  save_total_limit: 2
  seed: 42
  remove_unused_columns: false
  max_grad_norm: 1.0
  weight_decay: 0.1

#ddp:
#  ddp_find_unused_parameters: false
