name: Sync docs to Wiki

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'

jobs:
  sync_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Clone wiki repo
        run: |
          git clone https://x-access-token:${{ secrets.WIKI_TOKEN }}@github.com/EvilFreelancer/impruver.wiki.git wiki
      - name: Copy docs to wiki
        run: |
          cp -Rv docs/* wiki/
      - name: Fix relative links
        working-directory: wiki
        run: |
          find . -type f -name '*.md' -exec \
            sed -i -E 's|\[([^]]*)\]\(([^)]*)\)|[\1](https://github.com/EvilFreelancer/impruver/blob/main/\2)|g' {} +
      - name: Commit and push changes
        working-directory: wiki
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: auto-update wiki from docs"
            git push origin master
          else
            echo "No changes to commit"
          fi
